### ISSUE TITLE
Unable to receive alert email

### ISSUE THREAD

**Issue by sunnynew** [elasticfence/kaae#22] opened 2016-09-19 06:38 UTC
Hi, I unable to receive email alert from KaaE. I can see alerts under "Alarms" section of KaaE plugin dashboard.

I able to receive mail when sent through command line from the server where Kibana + KaaE is running.

    _echo "testing"|mail -s "testing" username@mycompany.com_ 

There is no username/password required to send email. I just need to specify email ID of recipient. [i tested Yelp/elastalert -- received alert by just giving email ID] Please suggest what setting i should put in kaae.json file. I even tried giving user and password but still no email in my inbox. 

**kaae.json**
   "settings" : {
    	"email" : {
    	   "user":	"",
    	   "password":	"",
    	   "host":	"relay.mycompany.com",
    	   "ssl":	true,
    	   "active":	false
    	},

**Below is the msg i get under kibana.log**
{"type":"log","@timestamp":"2016-09-19T06:23:00+00:00","tags":["status","info","KaaE"],"pid":26910,"message":"Executing watch: RPM Next Round of RPM at Sun Sep 18 2016 23:23:00 GMT-0700 (PDT)"}
{"type":"log","@timestamp":"2016-09-19T06:23:00+00:00","tags":["status","info","KaaE"],"pid":26910,"message":"Action Report requires Email Settings! Reports Disabled."}
{"type":"log","@timestamp":"2016-09-19T06:23:00+00:00","tags":["status","info","KaaE"],"pid":26910,"message":"Processing action: email_admin"}
{"type":"log","@timestamp":"2016-09-19T06:23:00+00:00","tags":["status","info","KaaE","email"],"pid":26910,"message":"Subject: KAAE ALARM , Body: Series Alarm : 76"}
{"type":"log","@timestamp":"2016-09-19T06:23:00+00:00","tags":["status","info","Kaae","email"],"pid":26910,"message":"Delivery Disabled!"}
{"type":"log","@timestamp":"2016-09-19T06:23:00+00:00","tags":["status","info","KaaE"],"pid":26910,"message":"Storing Alarm to ES with type:email_admin"}

**Comment by lmangani** [comment] 2016-09-19 07:34
Hi @sunnynew , in your configuration block you explicitly need to set active-ness.

This log-line tells the story:
```
["status","info","Kaae","email"],"pid":26910,"message":"Delivery Disabled!"}
```

You can resolve by changing the following parameter:
```
"active":  true
```

**Comment by sunnynew** [comment] 2016-09-19 08:09
Hi Imangani,

Thanks for quick response. After changing "active":  true, getting below exceptions.


{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","KaaE"],"pid":4746,"message":"Executing watch: RPM Next Round of RPM at Mon Sep 19 2016 00:57:00 GMT-0700 (PDT)"}
{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","KaaE"],"pid":4746,"message":"Processing action: email_admin"}
{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","KaaE","email"],"pid":4746,"message":"Subject: KAAE ALARM , Body: Series Alarm : 28"}
{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","Kaae","email"],"pid":4746,"message":"Delivering to Mail Server"}
{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","Kaae","email"],"pid":4746,"level":"error","message":"message is not a valid Message instance","error":{"message":"message is not a valid Message instance","name":"Error","stack":"Error: message is not a valid Message instance\n    at Object.Client.send (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/emailjs/smtp/client.js:122:19)\n    at /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/actions.js:125:27\n    at /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/lodash.js:4738:15\n    at baseForOwn (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/lodash.js:2879:24)\n    at Function.forOwn (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/lodash.js:12670:24)\n    at exports.default (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/actions.js:83:4)\n    at /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/scheduler.js:79:19\n    at tryCatcher (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:503:31)\n    at Promise._settlePromiseAt (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:577:18)\n    at Promise._settlePromises (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:693:14)\n    at Async._drainQueue (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"}


{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","KaaE"],"pid":4746,"message":"Executing watch: RPM Next Round of RPM at Mon Sep 19 2016 00:57:00 GMT-0700 (PDT)"}
{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","KaaE"],"pid":4746,"message":"Processing action: email_admin"}
{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","KaaE","email"],"pid":4746,"message":"Subject: KAAE ALARM , Body: Series Alarm : 28"}
{"type":"log","@timestamp":"2016-09-19T07:57:00+00:00","tags":["status","info","KaaE"],"pid":4746,"message":"Storing Alarm to ES with type:email_admin"}
Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17

**Comment by lmangani** [comment] 2016-09-19 08:18
Hi @sunnynew 

I suggest you activate one plugin at the time to ease troubleshooting. We'll need to see the watcher you scheduled as the issue seems to be with the body of the email you are trying to send, and with the absence of phantomjs for the Report issue, which needs to be available on the system upfront.

**Comment by sunnynew** [comment] 2016-09-19 09:14
Hi,

Sorry for any confusion, I am just using KaaE for alerting as of now. Below is my watcher -- simple one to alert if requests in access log went above 25.


_{
  "_index": "watcher",
  "_type": "watch",
  "_id": "RPM",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "input": {
      "search": {
        "request": {
          "indices": [
            "<access-{now/d}>",
            "<access-{now/d-1d}>"
          ],
          "body": {
            "size": 0,
            "query": {
              "filtered": {
                "query": {
                  "query_string": {
                    "analyze_wildcard": true,
                    "query": "*"
                  }
                },
                "filter": {
                  "range": {
                    "@timestamp": {
                      "from": "now-5m"
                    }
                  }
                }
              }
            },
            "aggs": {}
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 25"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "username@mycompany.com",
          "subject": "KAAE ALARM {{ payload._id }}",
          "priority": "high",
          "body": "Series Alarm {{ payload._id}}: {{ payload.hits.total }}"
        }
      }
    }
  }
}_

**Comment by sunnynew** [comment] 2016-09-19 09:28
phantomjs is installed.

[root@host opt]$ phantomjs /opt/phantomjs/examples/hello.js
Hello, world!

**Comment by sunnynew** [comment] 2016-09-19 10:00
As mentioned above getting below error.

{"type":"log","@timestamp":"2016-09-19T09:52:00+00:00","tags":["status","info","KaaE"],"pid":4746,"message":"Executing watch: RPM Next Round of RPM at Mon Sep 19 2016 02:52:00 GMT-0700 (PDT)"}
{"type":"log","@timestamp":"2016-09-19T09:52:00+00:00","tags":["status","info","KaaE"],"pid":4746,"message":"Processing action: email_admin"}
{"type":"log","@timestamp":"2016-09-19T09:52:00+00:00","tags":["status","info","KaaE","email"],"pid":4746,"message":"Subject: KAAE ALARM , Body: Series Alarm : 44"}
{"type":"log","@timestamp":"2016-09-19T09:52:00+00:00","tags":["status","info","Kaae","email"],"pid":4746,"message":"Delivering to Mail Server"}
{"type":"log","@timestamp":"2016-09-19T09:52:00+00:00","tags":["status","info","Kaae","email"],"pid":4746,"level":"error","message":"message is not a valid Message instance","error":{"message":"message is not a valid Message instance","name":"Error","stack":"Error: message is not a valid Message instance\n    at Object.Client.send (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/emailjs/smtp/client.js:122:19)\n    at /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/actions.js:125:27\n    at /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/lodash.js:4738:15\n    at baseForOwn (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/lodash.js:2879:24)\n    at Function.forOwn (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/lodash.js:12670:24)\n    at exports.default (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/actions.js:83:4)\n    at /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/scheduler.js:79:19\n    at tryCatcher (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:503:31)\n    at Promise._settlePromiseAt (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:577:18)\n    at Promise._settlePromises (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:693:14)\n    at Async._drainQueue (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"}}

**Comment by lmangani** [comment] 2016-09-19 10:48
Hi @sunnynew I see the problem now. You are missing the FROM email parameter which is mandatory.

**Comment by sunnynew** [comment] 2016-09-19 11:17
Hooray! Lovely!!  -- Start getting alerts :+1:   Thanks a ton @lmangani 

After adding FROM section in watcher, i got below error but i get rid of it by making **_ssl:false_** in kaae.json


{"type":"log","@timestamp":"2016-09-19T11:03:00+00:00","tags":["status","info","KaaE","email"],"pid":4746,"message":"Subject: KAAE ALARM , Body: Series Alarm : 36"}
{"type":"log","@timestamp":"2016-09-19T11:03:00+00:00","tags":["status","info","Kaae","email"],"pid":4746,"message":"Delivering to Mail Server"}
{"type":"log","@timestamp":"2016-09-19T11:03:00+00:00","tags":["status","info","KaaE"],"pid":4746,"message":"Storing Alarm to ES with type:email_admin"}
{"type":"log","@timestamp":"2016-09-19T11:03:00+00:00","tags":["status","info","Kaae","email"],"pid":4746,"level":"error","message":"connection encountered an error","error":{"message":"connection encountered an error","name":"Error","stack":"Error: connection encountered an error\n    at module.exports (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/emailjs/smtp/error.js:3:13)\n    at TLSSocket.error (/opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/emailjs/smtp/response.js:26:29)\n    at emitOne (events.js:82:20)\n    at TLSSocket.emit (events.js:169:7)\n    at emitErrorNT (net.js:1253:8)\n    at nextTickCallbackWith2Args (node.js:442:9)\n    at process._tickDomainCallback (node.js:397:17)","code":5}}

**Comment by sunnynew** [comment] 2016-09-19 11:23
Just a suggestion: when we create new watcher by clicking "**Set Watcher**" button under Visualize section in kibana FROM section is missing. That is why FROM section was missing from email parameter in my watcher config.

Thanks again!

**Comment by lmangani** [comment] 2016-09-19 11:25
Excellent! I'll extend the wiki with this information.
Glad its working now and don't hesitate to open new issues in case you find any.

Resolving.

**Closed by lmangani** 2016-09-19 11:25 UTC
Labels: question

**Comment by lmangani** [comment] 2016-09-19 14:55
I'm wondering if we should just determine the from in the snmp configuration directly and have it apply for all actions using it? Comments?

**Comment by sunnynew** [comment] 2016-09-20 05:14
Hi,

1). First check if FROM section is provided by user  under email parameter, if not
2). Pick from  snmp configuration directly

System shouldn't fail, some default should be picked.

Thanks!

**Comment by sunnynew** [comment] 2016-09-20 06:00
Hi @lmangani 

I would like to discuss issues related to hourly "Reporter" where we send snapshot of Alerts dashboard. 

**Issue 1)**
I have created a Kibana dashboard which is accessible as per URL defined. There are few report graphs added in that dashboard. I do receive a email with snapshot attached but report graphs are not visible, kind of blank Snapshot, just  **Discover | Visualize | Dashboard |  Setting** menu on top and blank white body without any graph/report.

```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "Hourly Report",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 hour"
      }
    },
    "report": true,
    "transform": {},
    "actions": {
      "report_admin": {
        "throttle_period": "15m",
        "report": {
          "to": "user@mycompany.com",
          "from": "kaae@mycompany.com",
          "subject": "KaaE Hourly Alert Report",
          "priority": "high",
          "body": "Sample KaaE Screenshot Report",
          "snapshot": {
            "res": "1280x900",
            "url": "http://<hostname>.com:5601/app/kibana#/dashboard/Alerts",
            "path": "/tmp/",
            "params": {
              "username": "",
              "password": "",
              "delay": 300,
              "crop": false
            }
          }
        }
      }
    }
  }
}
```
I tied increasing delay value in assumption that may be dashboard taking time to load completely. But that also doesn't help.

**Issue 2)**
I tested "Reporter" with 5 min interval. After each execution, one process remain in running state in the system. Kibana get crashed when # of such process increased overtime. I had to kill all these manually.

```
root       502  0.2  0.8 2453696 137760 pts/1  SNl  21:49   0:06 phantomjs --load-images=true --ssl-protocol=any /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/node-phantom-simple/bridge.js
root       951  0.2  0.8 2450508 137664 pts/1  SNl  21:54   0:06 phantomjs --load-images=true --ssl-protocol=any /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/node-phantom-simple/bridge.js
root      1401  0.2  0.8 2450280 137692 pts/1  SNl  21:59   0:05 phantomjs --load-images=true --ssl-protocol=any /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/node-phantom-simple/bridge.js
root      2274  0.2  0.8 2450248 140476 pts/1  SNl  22:04   0:05 phantomjs --load-images=true --ssl-protocol=any /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/node-phantom-simple/bridge.js
root      2707  0.3  0.9 2463208 146908 pts/1  SNl  22:09   0:05 phantomjs --load-images=true --ssl-protocol=any /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/node-phantom-simple/bridge.js
root      3149  0.3  0.8 2463148 144840 pts/1  SNl  22:14   0:05 phantomjs --load-images=true --ssl-protocol=any /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/node-phantom-simple/bridge.js
```

**Comment by sunnynew** [comment] 2016-09-20 06:17
Hi,

Snapshot issue resolved after i increased **delay: 5000**, it seems like value is in ms.

@lmangani please take a look at **phantomjs** thread issue which remain running after every **Reporter** execution.

Thanks!

**Comment by lmangani** [comment] 2016-09-20 06:44
Please open a new issue for PhantomJS so we can troubleshoot it. Have you followed the Wiki steps?
https://github.com/elasticfence/kaae/wiki/KAAE-Report-Example#requirements

**Comment by sunnynew** [comment] 2016-09-20 07:45
Sorry i didn't went through all Wiki steps.

Opened a new issue for PhantomJS

Thanks!

**Comment by sunnynew** [comment] 2016-09-20 11:34
@lmangani Do we have any KaaE 95th response time watcher example. 

I want watcher for 95th response time from access log which aggregated to elasticsearch. Field name : ResponeTime

**Comment by lmangani** [comment] 2016-09-20 11:54
You should be able to generate this from any visualizer using the [Kaae SPY extension](https://github.com/elasticfence/kaae/wiki/KAAE-SPY-Plugin). Create an aggregation with 95th percentile and adapt the output to use it following the [Aggs Watcher Example](https://github.com/elasticfence/kaae/wiki/KAAE-Watcher-Examples) (this might be a bit tricky at the beginning)

**Comment by sunnynew** [comment] 2016-09-20 16:43
Hi @lmangani 

can you please review below watcher -- getting "message":"Condition Error for 95th: SyntaxError: Unexpected number"}

```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "95th",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 5 minutes"
      }
    },
    "input": {
      "search": {
        "request": {
          "indices": [
            "<access-{now/d}>",
            "<access-{now/d-1d}>"
          ],
          "body": {
            "size": 0,
            "query": {
              "filtered": {
                "query": {
                  "query_string": {
                    "analyze_wildcard": true,
                    "query": "*"
                  }
                },
                "filter": {
                  "range": {
                    "@timestamp": {
                      "from": "now-5m"
                    }
                  }
                }
              }
            },
            "aggs": {
              "2": {
                "percentiles": {
                  "field": "response_time",
                  "percents": [
                    95
                  ]
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.aggregations.2.values.95 > 1000"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "username@mycompany.com",
          "from": "kaae@mycompany.com",
          "subject": "KAAE ALARM {{ payload._id }}",
          "priority": "high",
          "body": "Series Alarm {{ payload._id}}: {{ payload.aggregations.2.values.95 }}"
        }
      }
    }
  }
}
```

**Comment by sunnynew** [comment] 2016-09-20 17:28
Watcher for Avg Response time is working fine...

```
            "aggs": {
              "avg": {
                "avg": {
                  "field": "response_time"
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.aggregations.avg.value > 1000"
      }
```

**Comment by sunnynew** [comment] 2016-09-21 03:18
Just percentiles isn't working and keep giving below error

`{"type":"log","@timestamp":"2016-09-21T03:16:00+00:00","tags":["status","info","KaaE"],"pid":1871,"message":"Condition Error for 95th: SyntaxError: Unexpected number"}`



```
            "aggs": {
              "response_time_outlier": {
                "percentiles": {
                  "field": "response_time",
                  "percents": [
                    95
                  ]
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.aggregations.response_time_outlier.values.95.0 > 1500"
      }
    },
```

**Comment by lmangani** [comment] 2016-09-21 07:51
If you share the actual query response we can try figure this out

**Comment by sunnynew** [comment] 2016-09-21 08:49
**Elasticsearch response body**  

```
{
  "took": 14,
  "timed_out": false,
  "_shards": {
    "total": 6,
    "successful": 6,
    "failed": 0
  },
  "hits": {
    "total": 43386,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "response_time_outlier": {
      "values": {
        "95.0": 2007.6466
      }
    }
  }
}
```

**Comment by lmangani** [comment] 2016-09-21 09:08
I see. Could you try selecting the "95.0" field as follows:

```payload.aggregations.response_time_outlier.values['95.0']```

**Comment by sunnynew** [comment] 2016-09-21 09:32
Hi, giving below error


```
{"type":"log","@timestamp":"2016-09-21T09:27:00+00:00","tags":["status","info","KaaE"],"pid":5868,"message":"Executing watch: Stats log Failures Next Round of Stats log Failures at Wed Sep 21 2016 02:27:00 GMT-0700 (PDT)"}
{"type":"log","@timestamp":"2016-09-21T09:27:00+00:00","tags":["status","info","KaaE"],"pid":5868,"message":"Executing watch: 95th Next Round of 95th at Wed Sep 21 2016 02:27:00 GMT-0700 (PDT)"}
{"type":"log","@timestamp":"2016-09-21T09:27:00+00:00","tags":["status","info","KaaE"],"pid":5868,"message":"Condition Error for 95th: SyntaxError: Unexpected token ["}
{"type":"log","@timestamp":"2016-09-21T09:27:00+00:00","tags":["status","info","KaaE"],"pid":5868,"message":"Clearing watcher: 95th"}
{"type":"log","@timestamp":"2016-09-21T09:27:00+00:00","tags":["status","info","KaaE"],"pid":5868,"message":"Scheduled Watch: 95th every every 1 minutes"}

```

```
{"type":"log","@timestamp":"2016-09-21T09:28:00+00:00","tags":["status","info","KaaE"],"pid":5868,"message":"Executing watch: 95th Next Round of 95th at Wed Sep 21 2016 02:28:00 GMT-0700 (PDT)"}
{"type":"log","@timestamp":"2016-09-21T09:28:00+00:00","tags":["status","info","KaaE"],"pid":5868,"message":"Processing action: email_admin"}
{"type":"log","@timestamp":"2016-09-21T09:28:00+00:00","tags":["status","info","KaaE","email"],"pid":5868,"message":"Subject: 95th Search RT -- KAAE ALARM , Body: Series Alarm : "}
{"type":"log","@timestamp":"2016-09-21T09:28:00+00:00","tags":["status","info","Kaae","email"],"pid":5868,"message":"Delivering to Mail Server"}
{"type":"log","@timestamp":"2016-09-21T09:28:00+00:00","tags":["status","info","KaaE"],"pid":5868,"message":"Storing Alarm to ES with type:email_admin"}
Trace: { [Error: [mapper_parsing_exception] Field name [95.0] cannot contain '.']
  status: 400,
  message: '[mapper_parsing_exception] Field name [95.0] cannot contain \'.\'',
  path: '/watcher_alarms-2016.09.21/email_admin',
  query: { op_type: 'create' },
  body: 
   { error: 
      { root_cause: [Object],
        type: 'mapper_parsing_exception',
        reason: 'Field name [95.0] cannot contain \'.\'' },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field name [95.0] cannot contain \'.\'"}],"type":"mapper_parsing_exception","reason":"Field name [95.0] cannot contain \'.\'"},"status":400}',
  toString: [Function],
  toJSON: [Function] } undefined
    at /opt/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/actions.js:77:22
    at tryCatcher (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by lmangani** [comment] 2016-09-21 09:34
You just need to escape the high commas to let the value being interpreted as string, ie:
<pre>
payload.aggregations.response_time_outlier.values[\'95.0\']
</pre>

**Comment by sunnynew** [comment] 2016-09-21 09:39
KaaE editor doesn't allow -- says  _**Bad string**_

**Comment by sunnynew** [comment] 2016-09-21 10:38
Hi @lmangani 
I hope you are working on to get a fix :+1:

**Comment by lmangani** [comment] 2016-09-21 10:53
Hi @sunnynew this is not a bug but a syntax issue with fields containing a ```.``` in the key name - please experiment with the selection and update on the attempts and results, I'll help find a suitable way

**Comment by sunnynew** [comment] 2016-09-21 11:14
I am trying to get rid of . in the key name, tried all permutation and combination but nothing worked as yet :(
Nothing to escape . from key name.

**Comment by chenryn** [comment] 2016-09-21 14:13
The error is because kaae try to insert alarm into es, but fieldname contains `.`. Maybe you need to upgrade to es 2.4.0 which allowed dot in fieldname again.

**Comment by chenryn** [comment] 2016-09-21 14:19
The error is because kaae try to insert alarm into es, but fieldname contains `.`. Maybe you need to upgrade to es 2.4.0 which allowed dot in fieldname again.

**Comment by lmangani** [comment] 2016-09-22 16:46
Thanks to kaaemaster @chenryn we might have a solution for this scenario: 
https://github.com/elasticfence/kaae/commit/563bfa639cc0698f882e42bfee8bdaa23be2bb78

**Comment by sunnynew** [comment] 2016-09-23 02:54
That great news -- so are we going to release a batch for KaaE

**Comment by lmangani** [comment] 2016-09-23 09:49
Thanks - please open a new issue with the new results so we can track this properly
